### ISSUE TITLE
Jibri configuration issue

### ISSUE THREAD

**Issue by MallRoy** [jitsi/jibri#478]
We tried to configure Jibri in our Azure Ubuntu 18.04 VM. We tried multiple solutions nothing worked out. Please find the attached image
![screenshot](https://user-images.githubusercontent.com/54269166/165757842-2a7b7a5c-4923-4171-a6cc-004f2cb23e28.png)

**Comment by saghul** [comment]
We fixed the module name in the README yesterday 😄  https://github.com/jitsi/jibri#alsa-and-loopback-device

**Comment by MallRoy** [comment]
![azure-installation](https://user-images.githubusercontent.com/54269166/165906251-c867b610-9906-482e-aecb-6a86d42fe733.png)
We tried following this guide as well [Link](https://nerdonthestreet.com/s/15). 

Issue persists. can you please help us to resolve

**Comment by saghul** [comment]
You may need to install a different kernel package. Some cloud providers don't include this module in the base package. Not sure if that's the case for Azure, sorry.
